apiVersion: v1
kind: Service
metadata:
  name: lucal-test-redis-service
  labels:
    username: lucal
    env: test
spec:
  type: ClusterIP
  selector:
    app: lucal-test-redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379