
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lucal-test-redis-pvc
  labels:  
    username: lucal
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cinder-csi
  resources:
    requests:
      storage: 1Gi